name: example
description: An example app to show the use of Animation Text Kit.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit:
    path: ../
  lints: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/background.png

  fonts:
    - family: Canterbury
      fonts:
        - asset: assets/Canterbury.ttf

    - family: HelloStockholm
      fonts:
        - asset: assets/HelloStockholm.otf

    - family: Horizon
      fonts:
        - asset: assets/Horizon.otf

    - family: Bobbers
      fonts:
        - asset: assets/Bobbers.ttf

    - family: Agne
      fonts:
        - asset: assets/Agne.otf
