name: animated_text_kit
description: A flutter package project which contains a collection of cool and beautiful text animations.
version: 2.5.0
author: Ayush Agarwal <aagarwal9782@gmail.com>
homepage: https://github.com/aagarwal1012/Animated-Text-Kit/
maintainer: Ayush Agarwal (@aagarwal1012)

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=0.3.0 <2.0.0"
