name: animated_text_kit
description: A flutter package project which contains a collection of cool and beautiful text animations.
version: 3.0.2
homepage: https://github.com/aagarwal1012/Animated-Text-Kit/
maintainer: Ayush Agarwal (@aagarwal1012)

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"
